name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
trigger:
  batch: true
  branches:
    include:
    - master
    - rel/*
pr:
- '*'
resources:
  repositories:
  - repository: templates
    type:       github
    name:       thnetii/azure-pipelines
    endpoint:   github
jobs:
- template: templates/dotnetcore/azure-pipelines.yml@templates
  parameters:
    checkout:
    - checkout:   self
      submodules: true
    common:
      allProjects: |
        [Ss]ample/*/*.csproj
        [Ss]rc/*/*.csproj
        [Tt]est/*/*.csproj
      srcProjects: |
        [Ss]rc/*/*.csproj
    windowsRuntime:
      common:
        allProjects: |
          [Ss]ample/*/*.csproj
          [Ss]rc/*/*.csproj
          [Tt]est/*/*.csproj
          [Ss]ample-win/*/*.csproj
          [Ss]rc-win/*/*.csproj
          [Tt]est-win/*/*.csproj
        testProjects: |
          [Tt]est/*/*.csproj
          [Tt]est-win/*/*.csproj
      arguments:    '-p:NoNetFramework=true'
    linuxRuntime:
      common:
        allProjects: |
          [Ss]ample/*/*.csproj
          [Ss]rc/*/*.csproj
          [Tt]est/*/*.csproj
          [Ss]ample-gtk/*/*.csproj
          [Ss]rc-gtk/*/*.csproj
          [Tt]est-gtk/*/*.csproj
        testProjects: |
          [Tt]est/*/*.csproj
          [Tt]est-gtk/*/*.csproj
    macRuntime:
      argValue:     osx.10.10-x64
      common:
        allProjects: |
          [Ss]ample/*/*.csproj
          [Ss]rc/*/*.csproj
          [Tt]est/*/*.csproj
          [Ss]ample-mac/*/*.csproj
          [Ss]rc-mac/*/*.csproj
          [Tt]est-mac/*/*.csproj
        testProjects: |
          [Tt]est/*/*.csproj
          [Tt]est-mac/*/*.csproj
